spring:
  application:
    name: threadvine
    version: 1.0.0

  datasource:
    username: ${DB_USER_NAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '9090'
jwt:
  secret: secret123345456ioedhfoshdfowisfosidfioshdfiushdfiusdjufhsdihfisduhfiusdhfuihsdifuhsidhfisudhfish
  expiration: 86400000L
